# Travis CI (https://travis-ci.org/)

language: c
dist: bionic # based on bionic beaver ubuntu distribution
cache:
  apt: true # only works with Pro version

env:
  global: # define environment variables for bash
    - OCTFLAGS="--no-gui --no-window-system --silent"

before_install:
  - travis_retry sudo apt-get -y -qq update
  # install octave
  - travis_retry sudo apt-get -y install octave
  - travis_retry sudo apt-get -y install liboctave-dev
  # install javascript
  - travis_retry sudo apt-get -y install nodejs
  - travis_retry sudo apt-get -y install npm
  # install miss_hit linter
  - cd .. && git clone https://github.com/florianschanda/miss_hit.git && export PATH=$PATH:`pwd`/miss_hit && cd CPP_BIDS


install:
  # make octave file the JSONio submodule
  - cd lib/JSONio; mkoctfile --mex jsonread.c jsmn.c -DJSMN_PARENT_LINKS; cd ../..
  - octave $OCTFLAGS --eval "addpath (pwd); savepath ();"
  # Install BIDS-Validator
  - sudo npm install -g bids-validator

before_script:
  # Add to src functions to path
  - octave $OCTFLAGS --eval "addpath(genpath(fullfile(pwd, 'src'))); savepath ();"
  # Change current directory
  - cd manualTests

jobs:
  include:
    - stage: "BIDS validator"
      name: "Create and check dataset"
      script: octave $OCTFLAGS --eval "test_makeRawDataset" && bids-validator `pwd`/output/rawdata/ --ignoreNiftiHeaders
    - stage: "Linter"
      name: "miss_hit"
      script: cd .. && mh_style `pwd`
      
    